#version 450
#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_shader_subgroup_shuffle : enable
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_EXT_control_flow_attributes : enable
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_shader_explicit_arithmetic_types: require
#extension GL_EXT_shader_explicit_arithmetic_types_int64: require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_float64 : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require

layout(local_size_x = 8, local_size_y = 16, local_size_z = 1) in;

struct read_cache_entry {
	uint index;
	bool stored;
};

#define zero_entry = read_cache_entry(0, false)
#define ZERO_CACHE(buf, size) { 	if (gl_LocalInvocationID.x == gl_LocalInvocationID.y == gl_LocalInvocationID.z == 0) 	{ 		for (uint i = 0; i < size; i += 1) buf[i] = zero_entry; 	} 	barrier(); } 
struct vec16 {
	float data[16];
};

vec16 make_vec16(float x0, float x1, float x2, float x3, float x4, float x5, float x6, float x7, float x8, float x9, float x10, float x11, float x12, float x13, float x14, float x15)
{
	return vec16(float[16](x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15) );
}

#define ZERO_VEC16 make_vec16(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)

float dot(vec16 a, vec16 b)
{
	float d = 0.0;
	for (uint i = 0; i < 16; i += 4)
	{
		vec4 a4 = vec4(a.data[i], a.data[i+1], a.data[i+2], a.data[i+3]);
		vec4 b4 = vec4(b.data[i], b.data[i+1], b.data[i+2], b.data[i+3]);
		d += dot(a4, b4);
	}
	return d;
}

vec16 add(vec16 a, vec16 b)
{
	vec16 d = ZERO_VEC16;
	for (uint i = 0; i < 16; i += 4)
	{
		vec4 a4 = vec4(a.data[i], a.data[i+1], a.data[i+2], a.data[i+3]);
		vec4 b4 = vec4(b.data[i], b.data[i+1], b.data[i+2], b.data[i+3]);
		vec4 c = a4 + b4;
		d.data[i] += c[0];
		d.data[i+1] += c[1];
		d.data[i+2] += c[2];
		d.data[i+3] += c[3];
	}
	return d;
}

vec16 mul(vec16 a, vec16 b)
{
	vec16 d = ZERO_VEC16;
	for (uint i = 0; i < 16; i += 4)
	{
		vec4 a4 = vec4(a.data[i], a.data[i+1], a.data[i+2], a.data[i+3]);
		vec4 b4 = vec4(b.data[i], b.data[i+1], b.data[i+2], b.data[i+3]);
		vec4 c = a4 * b4;
		d.data[i] += c[0];
		d.data[i+1] += c[1];
		d.data[i+2] += c[2];
		d.data[i+3] += c[3];
	}
	return d;
}

struct vec8 {
	float data[8];
};

vec8 make_vec8(float x0, float x1, float x2, float x3, float x4, float x5, float x6, float x7)
{
	return vec8(float[8](x0, x1, x2, x3, x4, x5, x6, x7) );
}

#define ZERO_VEC8 make_vec8(0,0,0,0,0,0,0,0)

float dot(vec8 a, vec8 b)
{
	float d = 0.0;
	for (uint i = 0; i < 8; i += 4)
	{
		vec4 a4 = vec4(a.data[i], a.data[i+1], a.data[i+2], a.data[i+3]);
		vec4 b4 = vec4(b.data[i], b.data[i+1], b.data[i+2], b.data[i+3]);
		d += dot(a4, b4);
	}
	return d;
}

vec8 add(vec8 a, vec8 b)
{
	vec8 d = ZERO_VEC8;
	for (uint i = 0; i < 8; i += 4)
	{
		vec4 a4 = vec4(a.data[i], a.data[i+1], a.data[i+2], a.data[i+3]);
		vec4 b4 = vec4(b.data[i], b.data[i+1], b.data[i+2], b.data[i+3]);
		vec4 c = a4 + b4;
		d.data[i] += c[0];
		d.data[i+1] += c[1];
		d.data[i+2] += c[2];
		d.data[i+3] += c[3];
	}
	return d;
}

vec8 mul(vec8 a, vec8 b)
{
	vec8 d = ZERO_VEC8;
	for (uint i = 0; i < 8; i += 4)
	{
		vec4 a4 = vec4(a.data[i], a.data[i+1], a.data[i+2], a.data[i+3]);
		vec4 b4 = vec4(b.data[i], b.data[i+1], b.data[i+2], b.data[i+3]);
		vec4 c = a4 * b4;
		d.data[i] += c[0];
		d.data[i+1] += c[1];
		d.data[i+2] += c[2];
		d.data[i+3] += c[3];
	}
	return d;
}

vec16 WMMA_4_4_1_float_float(vec4 a, vec4 b, vec16 c)
{
	return ZERO_VEC16;
}

float WMMA_1_1_1_float_float(float a, float b, float c)
{
	return fma(a, b, c);
}

vec8 WMMA_16_16_16_float_float(vec16 a, vec16 b, vec8 c)
{
	// warp size of 32 assumed
	// so C is assigned by columns...
	// and if C is assigned by columns, that means...
	// hmm.
	// well I think the best thing to do is multiply a by b, first of all
	vec16 intermediate = mul(a, b);
	
	// once we have the intermediate, things get a bit tricky.
	// each warp should have 2 of these intermediates stored in it.
	// so we have to take the vector element (emulated VGPR)
	// and somehow broadcast it across all the other subgroup lanes.
	// So it looks like the C element is the K index // 2.
	// And there are of course 32 different c vectors, since that is the number of threads per wave.
	// Then does the intermediate (a*b) value go into the lower half, or the upper half?
	// It seems that if the K index is even, it goes in the lower half.
	// If the K index is odd, it goes in the upper half.
	// Sooo...how to get the K index?
	// should be:
	uint k = gl_SubgroupID;
	bool lower = true;
	if (k >= 16)
	{
		lower = false;
		k -= 16;
	}
	// this is nicer. if the subgroup ID is 16 or over, it gets put in the upper half. thats more straightforward
	// now I just need to figure out a way to convert gl_SubgroupID to the element of D that is being used.
	// and I have no idea how to do that. so for now, we wait :c
	
	return c;
}

#if 0
vec4 WMMA_2_2_1_float_float(vec2 a, vec2 b, vec4 c)
{
	mat2 ab = outerProduct(a);
	return c + vec4(ab[0][0], ab[0][1], ab[1][0], ab[1][1]);
}
#endif
#define ADDR_T uint64_t
#define INFINITY uintBitsToFloat(0x7F800000)
#define NAN uintBitsToFloat(0x7FC00000)
#define PI 3.14159265358979323846
#define STORE_VEC(buf, idx, vector, size, VEC_T) { VEC_T tmpV = vector; for (uint i = 0; i < size; i += 1) buf[idx + i] = tmpV[i]; }
#define LOAD_VEC2(buf, idx, VEC_T) VEC_T(buf[idx], buf[idx + 1])
#define LOAD_VEC4(buf, idx, VEC_T) VEC_T(buf[idx], buf[idx + 1], buf[idx + 2], buf[idx + 3])
precise float exp2_precise(float t) { precise float s = exp2(t); return s; }
precise float log2_precise(float t) { if (t == 0.0) return -1.0*INFINITY; precise float s = log2(t); return s; }

precise float64_t exp2(float64_t x) { precise float tmp =  float(x); tmp = pow(2.0, tmp); return float64_t(tmp); }
precise float64_t exp2_precise(float64_t t) { precise float64_t s = exp2(t); return s; }
precise float64_t log2_precise(float64_t t) { if (t == 0.0) return float64_t(-1.0*INFINITY); precise float s = log2(float(t)); return float64_t(s); }

precise float16_t exp2_precise(float16_t t) { precise float16_t s = exp2(t); return s; }
precise float16_t log2_precise(float16_t t) { if (t == 0.0) return float16_t(-1.0*INFINITY); precise float16_t s = log2(t); return s; }
layout(buffer_reference, std140, buffer_reference_align = 16) buffer double_ptr { double data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer float_ptr { float data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uint8_t_ptr { uint8_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uint16_t_ptr { uint16_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer int16_t_ptr { int16_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer int8_t_ptr { int8_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer int_ptr { int data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer int64_t_ptr { int64_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uint64_t_ptr { uint64_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uint_ptr { uint data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer float16_t_ptr { float16_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer vec2_ptr { vec2 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer vec4_ptr { vec4 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer f16vec2_ptr { f16vec2 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer f16vec4_ptr { f16vec4 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer ivec2_ptr { ivec2 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer ivec4_ptr { ivec4 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uvec2_ptr { uvec2 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uvec4_ptr { uvec4 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer bvec2_ptr { bvec2 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer bvec4_ptr { bvec4 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 32) buffer vec8_ptr { vec8 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 64) buffer vec16_ptr { vec16 data[]; };

float nan() { uint bits = 0xffffffffu; return uintBitsToFloat(bits); }
layout(push_constant) uniform push_consts { 	ADDR_T data0_65536; 	ADDR_T data1_256; } push;
void main()
{
  int gidx0 = int(gl_WorkGroupID.x); /* 4 */
  int lidx0 = int(gl_LocalInvocationID.x); /* 8 */
  int lidx1 = int(gl_LocalInvocationID.y); /* 16 */
  int gidx1 = int(gl_WorkGroupID.y); /* 32 */
  float val0 = float_ptr(push.data1_256 + (lidx0+(gidx1<<(3)))*4).data[0];
  vec4_ptr(push.data0_65536 + (((gidx0<<(6))+(lidx1<<(2))+(gidx1<<(11))+(lidx0<<(8)))*4)).data[0] = vec4(val0,val0,val0,val0);
}
