#version 450
#extension GL_EXT_control_flow_attributes : enable
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_shader_explicit_arithmetic_types: require
#extension GL_EXT_shader_explicit_arithmetic_types_int64: require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_float64 : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct read_cache_entry {
	uint index;
	bool stored;
};

#define zero_entry = read_cache_entry(0, false)
#define ZERO_CACHE(buf, size) { 	if (gl_LocalInvocationID.x == gl_LocalInvocationID.y == gl_LocalInvocationID.z == 0) 	{ 		for (uint i = 0; i < size; i += 1) buf[i] = zero_entry; 	} 	barrier(); } 

#define ADDR_T uint64_t
#define INFINITY uintBitsToFloat(0x7F800000)
#define NAN uintBitsToFloat(0x7FC00000)
#define PI 3.14159265358979323846
#define STORE_VEC(buf, idx, vector, size, VEC_T) { VEC_T tmpV = vector; for (uint i = 0; i < size; i += 1) buf[idx + i] = tmpV[i]; }
#define LOAD_VEC2(buf, idx, VEC_T) VEC_T(buf[idx], buf[idx + 1])
#define LOAD_VEC4(buf, idx, VEC_T) VEC_T(buf[idx], buf[idx + 1], buf[idx + 2], buf[idx + 3])
precise float exp2_precise(float t) { precise float s = exp2(t); return s; }
precise float log2_precise(float t) { if (t == 0.0) return -1.0*INFINITY; precise float s = log2(t); return s; }

precise float64_t exp2(float64_t x) { precise float tmp =  float(x); tmp = pow(2.0, tmp); return float64_t(tmp); }
precise float64_t exp2_precise(float64_t t) { precise float64_t s = exp2(t); return s; }
precise float64_t log2_precise(float64_t t) { if (t == 0.0) return float64_t(-1.0*INFINITY); precise float s = log2(float(t)); return float64_t(s); }

precise float16_t exp2_precise(float16_t t) { precise float16_t s = exp2(t); return s; }
precise float16_t log2_precise(float16_t t) { if (t == 0.0) return float16_t(-1.0*INFINITY); precise float16_t s = log2(t); return s; }
layout(buffer_reference, std140, buffer_reference_align = 16) buffer double_ptr { double data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer float_ptr { float data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uint8_t_ptr { uint8_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uint16_t_ptr { uint16_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer int16_t_ptr { int16_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer int8_t_ptr { int8_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer int_ptr { int data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer int64_t_ptr { int64_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uint64_t_ptr { uint64_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uint_ptr { uint data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer float16_t_ptr { float16_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer vec2_ptr { vec2 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer vec4_ptr { vec4 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer f16vec2_ptr { f16vec2 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer f16vec4_ptr { f16vec4 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer ivec2_ptr { ivec2 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer ivec4_ptr { ivec4 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uvec2_ptr { uvec2 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uvec4_ptr { uvec4 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer bvec2_ptr { bvec2 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer bvec4_ptr { bvec4 data[]; };

float nan() { uint bits = 0xffffffffu; return uintBitsToFloat(bits); }
layout(push_constant) uniform push_consts { 	ADDR_T data0_1; 	ADDR_T data1_6; } push;
void main()
{
  int val0 = int_ptr(push.data1_6 + (0)*4).data[0];
  int val1 = int_ptr(push.data1_6 + (1)*4).data[0];
  int val2 = int_ptr(push.data1_6 + (2)*4).data[0];
  int val3 = int_ptr(push.data1_6 + (3)*4).data[0];
  int val4 = int_ptr(push.data1_6 + (4)*4).data[0];
  int val5 = int_ptr(push.data1_6 + (5)*4).data[0];
  uint8_t alu0 = ((uint8_t(val0))^(uint8_t(-1u)));
  uint8_t alu1 = ((uint8_t(val1))^(uint8_t(-1u)));
  uint8_t alu2 = ((uint8_t(val2))^(uint8_t(-1u)));
  uint8_t alu3 = ((uint8_t(val3))^(uint8_t(-1u)));
  uint8_t alu4 = ((uint8_t(val4))^(uint8_t(-1u)));
  uint8_t alu5 = ((uint8_t(val5))^(uint8_t(-1u)));
  uint8_t alu6 = (alu0<alu1) ? alu1 : alu0;
  uint8_t alu7 = (alu6<alu2) ? alu2 : alu6;
  uint8_t alu8 = (alu7<alu3) ? alu3 : alu7;
  uint8_t alu9 = (alu8<alu4) ? alu4 : alu8;
  uint8_t alu10 = (alu9<alu5) ? alu5 : alu9;
  uint8_t_ptr(push.data0_1 + (0)*1).data[0] = (alu10^(uint8_t(-1u)));
}
