#version 450
#extension GL_EXT_control_flow_attributes : enable
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_shader_explicit_arithmetic_types: require
#extension GL_EXT_shader_explicit_arithmetic_types_int64: require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_float64 : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require

layout(local_size_x = 8, local_size_y = 16, local_size_z = 1) in;

struct read_cache_entry {
	uint index;
	bool stored;
};

#define zero_entry = read_cache_entry(0, false)
#define ZERO_CACHE(buf, size) { 	if (gl_LocalInvocationID.x == gl_LocalInvocationID.y == gl_LocalInvocationID.z == 0) 	{ 		for (uint i = 0; i < size; i += 1) buf[i] = zero_entry; 	} 	barrier(); } 
struct vec16 {
	float data[16];
};

vec16 make_vec16(float x0, float x1, float x2, float x3, float x4, float x5, float x6, float x7, float x8, float x9, float x10, float x11, float x12, float x13, float x14, float x15)
{
	return vec16(float[16](x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15) );
}

#define ZERO_VEC16 make_vec16(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)

float dot(vec16 a, vec16 b)
{
	float d = 0.0;
	for (uint i = 0; i < 16; i += 4)
	{
		vec4 a4 = vec4(a.data[i], a.data[i+1], a.data[i+2], a.data[i+3]);
		vec4 b4 = vec4(b.data[i], b.data[i+1], b.data[i+2], b.data[i+3]);
		d += dot(a4, b4);
	}
	return d;
}

vec16 add(vec16 a, vec16 b)
{
	vec16 d = ZERO_VEC16;
	for (uint i = 0; i < 16; i += 4)
	{
		vec4 a4 = vec4(a.data[i], a.data[i+1], a.data[i+2], a.data[i+3]);
		vec4 b4 = vec4(b.data[i], b.data[i+1], b.data[i+2], b.data[i+3]);
		vec4 c = a4 + b4;
		d.data[i] += c[0];
		d.data[i+1] += c[1];
		d.data[i+2] += c[2];
		d.data[i+3] += c[3];
	}
	return d;
}

vec16 WMMA_4_4_1_float_float(vec4 a, vec4 b, vec16 c)
{
	return ZERO_VEC16;
}

float WMMA_1_1_1_float_float(float a, float b, float c)
{
	return fma(a, b, c);
}
#if 0
vec4 WMMA_2_2_1_float_float(vec2 a, vec2 b, vec4 c)
{
	mat2 ab = outerProduct(a);
	return c + vec4(ab[0][0], ab[0][1], ab[1][0], ab[1][1]);
}
#endif
#define ADDR_T uint64_t
#define INFINITY uintBitsToFloat(0x7F800000)
#define NAN uintBitsToFloat(0x7FC00000)
#define PI 3.14159265358979323846
#define STORE_VEC(buf, idx, vector, size, VEC_T) { VEC_T tmpV = vector; for (uint i = 0; i < size; i += 1) buf[idx + i] = tmpV[i]; }
#define LOAD_VEC2(buf, idx, VEC_T) VEC_T(buf[idx], buf[idx + 1])
#define LOAD_VEC4(buf, idx, VEC_T) VEC_T(buf[idx], buf[idx + 1], buf[idx + 2], buf[idx + 3])
precise float exp2_precise(float t) { precise float s = exp2(t); return s; }
precise float log2_precise(float t) { if (t == 0.0) return -1.0*INFINITY; precise float s = log2(t); return s; }

precise float64_t exp2(float64_t x) { precise float tmp =  float(x); tmp = pow(2.0, tmp); return float64_t(tmp); }
precise float64_t exp2_precise(float64_t t) { precise float64_t s = exp2(t); return s; }
precise float64_t log2_precise(float64_t t) { if (t == 0.0) return float64_t(-1.0*INFINITY); precise float s = log2(float(t)); return float64_t(s); }

precise float16_t exp2_precise(float16_t t) { precise float16_t s = exp2(t); return s; }
precise float16_t log2_precise(float16_t t) { if (t == 0.0) return float16_t(-1.0*INFINITY); precise float16_t s = log2(t); return s; }
layout(buffer_reference, std140, buffer_reference_align = 16) buffer double_ptr { double data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer float_ptr { float data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uint8_t_ptr { uint8_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uint16_t_ptr { uint16_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer int16_t_ptr { int16_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer int8_t_ptr { int8_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer int_ptr { int data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer int64_t_ptr { int64_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uint64_t_ptr { uint64_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uint_ptr { uint data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer float16_t_ptr { float16_t data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer vec2_ptr { vec2 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer vec4_ptr { vec4 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer f16vec2_ptr { f16vec2 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer f16vec4_ptr { f16vec4 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer ivec2_ptr { ivec2 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer ivec4_ptr { ivec4 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uvec2_ptr { uvec2 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer uvec4_ptr { uvec4 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer bvec2_ptr { bvec2 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 16) buffer bvec4_ptr { bvec4 data[]; };
layout(buffer_reference, std140, buffer_reference_align = 64) buffer vec16_ptr { vec16 data[]; };

float nan() { uint bits = 0xffffffffu; return uintBitsToFloat(bits); }
layout(push_constant) uniform push_consts { 	ADDR_T data0_65536; 	ADDR_T data1_65536; 	ADDR_T data2_65536; } push;
void main()
{
  float acc0[16];
  int gidx0 = int(gl_WorkGroupID.x); /* 4 */
  int gidx1 = int(gl_WorkGroupID.y); /* 8 */
  int lidx0 = int(gl_LocalInvocationID.x); /* 8 */
  int lidx1 = int(gl_LocalInvocationID.y); /* 16 */
  acc0[(0)] = float(0.0f);
  acc0[(1)] = float(0.0f);
  acc0[(2)] = float(0.0f);
  acc0[(3)] = float(0.0f);
  acc0[(4)] = float(0.0f);
  acc0[(5)] = float(0.0f);
  acc0[(6)] = float(0.0f);
  acc0[(7)] = float(0.0f);
  acc0[(8)] = float(0.0f);
  acc0[(9)] = float(0.0f);
  acc0[(10)] = float(0.0f);
  acc0[(11)] = float(0.0f);
  acc0[(12)] = float(0.0f);
  acc0[(13)] = float(0.0f);
  acc0[(14)] = float(0.0f);
  acc0[(15)] = float(0.0f);
  int alu16 = ((gidx1<<(13))+(lidx0<<(10)));
  int alu17 = ((gidx0<<(6))+(lidx1<<(2)));
  for (int Ridx0 = 0; Ridx0 < (64); Ridx0++) {
    int alu18 = (alu16+(Ridx0<<(2)));
    vec4 val0 = vec4_ptr(push.data1_65536 + (alu18*4)).data[0];
    vec4 val1 = vec4_ptr(push.data1_65536 + ((alu18+(256))*4)).data[0];
    vec4 val2 = vec4_ptr(push.data1_65536 + ((alu18+(512))*4)).data[0];
    vec4 val3 = vec4_ptr(push.data1_65536 + ((alu18+(768))*4)).data[0];
    int alu19 = (alu17+(Ridx0<<(10)));
    vec4 val4 = vec4_ptr(push.data2_65536 + (alu19*4)).data[0];
    vec4 val5 = vec4_ptr(push.data2_65536 + ((alu19+(256))*4)).data[0];
    vec4 val6 = vec4_ptr(push.data2_65536 + ((alu19+(512))*4)).data[0];
    vec4 val7 = vec4_ptr(push.data2_65536 + ((alu19+(768))*4)).data[0];
    acc0[(1)] = float((acc0[(1)]+(val1[0]*val4[0])+(val1[1]*val5[0])+(val1[2]*val6[0])+(val1[3]*val7[0])));
    acc0[(5)] = float((acc0[(5)]+(val1[0]*val4[1])+(val1[1]*val5[1])+(val1[2]*val6[1])+(val1[3]*val7[1])));
    acc0[(9)] = float((acc0[(9)]+(val1[0]*val4[2])+(val1[1]*val5[2])+(val1[2]*val6[2])+(val1[3]*val7[2])));
    acc0[(13)] = float((acc0[(13)]+(val1[0]*val4[3])+(val1[1]*val5[3])+(val1[2]*val6[3])+(val1[3]*val7[3])));
    acc0[(2)] = float((acc0[(2)]+(val2[0]*val4[0])+(val2[1]*val5[0])+(val2[2]*val6[0])+(val2[3]*val7[0])));
    acc0[(6)] = float((acc0[(6)]+(val2[0]*val4[1])+(val2[1]*val5[1])+(val2[2]*val6[1])+(val2[3]*val7[1])));
    acc0[(10)] = float((acc0[(10)]+(val2[0]*val4[2])+(val2[1]*val5[2])+(val2[2]*val6[2])+(val2[3]*val7[2])));
    acc0[(14)] = float((acc0[(14)]+(val2[0]*val4[3])+(val2[1]*val5[3])+(val2[2]*val6[3])+(val2[3]*val7[3])));
    acc0[(3)] = float((acc0[(3)]+(val3[0]*val4[0])+(val3[1]*val5[0])+(val3[2]*val6[0])+(val3[3]*val7[0])));
    acc0[(7)] = float((acc0[(7)]+(val3[0]*val4[1])+(val3[1]*val5[1])+(val3[2]*val6[1])+(val3[3]*val7[1])));
    acc0[(11)] = float((acc0[(11)]+(val3[0]*val4[2])+(val3[1]*val5[2])+(val3[2]*val6[2])+(val3[3]*val7[2])));
    acc0[(15)] = float((acc0[(15)]+(val3[0]*val4[3])+(val3[1]*val5[3])+(val3[2]*val6[3])+(val3[3]*val7[3])));
    acc0[(0)] = float((acc0[(0)]+(val0[0]*val4[0])+(val0[1]*val5[0])+(val0[2]*val6[0])+(val0[3]*val7[0])));
    acc0[(4)] = float((acc0[(4)]+(val0[0]*val4[1])+(val0[1]*val5[1])+(val0[2]*val6[1])+(val0[3]*val7[1])));
    acc0[(8)] = float((acc0[(8)]+(val0[0]*val4[2])+(val0[1]*val5[2])+(val0[2]*val6[2])+(val0[3]*val7[2])));
    acc0[(12)] = float((acc0[(12)]+(val0[0]*val4[3])+(val0[1]*val5[3])+(val0[2]*val6[3])+(val0[3]*val7[3])));
  }
  int alu37 = (alu17+alu16);
  vec4_ptr(push.data0_65536 + (alu37*4)).data[0] = vec4(acc0[(0)],acc0[(4)],acc0[(8)],acc0[(12)]);
  vec4_ptr(push.data0_65536 + ((alu37+(256))*4)).data[0] = vec4(acc0[(1)],acc0[(5)],acc0[(9)],acc0[(13)]);
  vec4_ptr(push.data0_65536 + ((alu37+(512))*4)).data[0] = vec4(acc0[(2)],acc0[(6)],acc0[(10)],acc0[(14)]);
  vec4_ptr(push.data0_65536 + ((alu37+(768))*4)).data[0] = vec4(acc0[(3)],acc0[(7)],acc0[(11)],acc0[(15)]);
}
